version: "3"

services:
  reverse-proxy:
    image: traefik:v2.9.9
    # command: --providers.docker && sh -c "apk add tcpdump && apk add python3 && python3 test_tcpdump.py"
    ports:
      - "88:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
  
  origin:
    image: python
    entrypoint: bash -c "mkdir /app && cd /app && echo 'It works!' > index.html && python -m http.server 80"
    labels:
      - "traefik.http.routers.origin.rule=Host(`origin.docker.localhost`)"
      - "traefik.http.services.origin.loadbalancer.server.port=80"

  # origin:
  #   image: python:3.6.9-alpine
  #   volumes:
  #     - /home/lzy/pcap/origin/traefik:/pcap
  #     - /home/lzy/logs/traefik:/logs
  #     - /home/lzy/my_repo/http2smuggler/echo_server/echo_server.py:/echo_server.py
  #     - /home/lzy/my_repo/http2smuggler/echo_server/requirements.txt:/requirements.txt
  #     - /home/lzy/my_repo/http2smuggler/echo_server/test_tcpdump.py:/test_tcpdump.py
  #   command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"
  #   labels:
  #       - "traefik.http.routers.origin.rule=Host(`origin.docker.localhost`)"
  #       - "traefik.http.services.origin.loadbalancer.server.port=80"


