version: "3"

services:

  reverse-proxy:
    image: haproxy:2.8-dev6-alpine3.17
    user: "0:0"
    ports:
      - 85:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

    depends_on:
      - origin

  origin:
    image: python
    entrypoint: bash -c "mkdir /app && cd /app && echo 'Origin works!' > index.html && python -m http.server 80"
  # origin:
  #   image: python:3.6.9-alpine
  #   volumes:
  #     - /home/lzy/pcap/origin/haproxy:/pcap
  #     - /home/lzy/logs/haproxy:/logs
  #     - /home/lzy/my_repo/http2smuggler/echo_server/echo_server.py:/echo_server.py
  #     - /home/lzy/my_repo/http2smuggler/echo_server/requirements.txt:/requirements.txt
  #     - /home/lzy/my_repo/http2smuggler/echo_server/test_tcpdump.py:/test_tcpdump.py
  #   command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"
